services:
  db:
    image: postgres:16-alpine
    container_name: bernerspace-db
    environment:
      POSTGRES_DB: mcp_server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  app:
    build: .
    container_name: bernerspace-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/mcp_server
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
