"""add integration_type to oauth_tokens

Revision ID: cbe457d6078c
Revises: 0097a46f2bcc
Create Date: 2025-08-09 02:03:22.416654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cbe457d6078c'
down_revision: Union[str, None] = '0097a46f2bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_tokens', sa.Column('integration_type', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_oauth_tokens_integration_type'), 'oauth_tokens', ['integration_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_tokens_integration_type'), table_name='oauth_tokens')
    op.drop_column('oauth_tokens', 'integration_type')
    # ### end Alembic commands ###
